apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heroes
  template:
    metadata:
      labels:
        app: heroes
    spec:
      containers:
        - name: dev-heroes
          image: petrovtoncho/heroes
          ports:
            - name: h-port
              containerPort: 8081
          env:
            - name: RABBITMQ_HOSTNAME
              value: rabbit-service
            - name: MONGO_HOSTNAME
              value: mongo-service