apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heroes
  template:
    metadata:
      labels:
        app: heroes
    spec:
      containers:
        - name: heroes
          image: petrovtoncho/heroes
          ports:
            - name: h-port
              containerPort: 8081
            - name: d-port-heroes
              containerPort: 5005
          resources:
            requests:
              cpu: 200m
          livenessProbe:
            httpGet:
              port: h-port
              path: /api/marvel/heroes/isAlive
            timeoutSeconds: 30
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              port: h-port
              path: /api/marvel/heroes/isAlive
            initialDelaySeconds: 15
            timeoutSeconds: 30
          env:
            - name: RABBITMQ_HOSTNAME
              value: rabbit-service
            - name: MONGO_HOSTNAME
              value: mongo-service
            - name: "JAVA_ENABLE_DEBUG"
              value: "true"
            - name: JAVA_DEBUG_PORT
              value: "5005"
---
# before use autoscaling need to enable metrics server
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: heroes-as
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: heroes
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50