apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
              name: mongo-port
          livenessProbe:
            httpGet:
              path: /
              port: mongo-port
            initialDelaySeconds: 15
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              port: mongo-port
              path: /
            initialDelaySeconds: 15
            timeoutSeconds: 30
          env:
            - name: MONGO_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MONGO_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP