apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
  labels:
    app: mongo
spec:
  storageClassName: mongo-storage
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi