apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    app: local
spec:
  volumeMode: Filesystem
  storageClassName: mongo-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: /home/mongo
