apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  ports:
    - name: mongo-port
      port: 27017
      protocol: TCP
      nodePort: 27017
  selector:
    app: mongo
