apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:management
          ports:
            - containerPort: 5672
              name: port-5672
          env:
            - name: RABBITMQ_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RABBIT_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP