apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  labels:
    app: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:management
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amqp
              protocol: TCP
              containerPort: 5672
          livenessProbe:
            exec:
              command: ["rabbitmqctl", "status"]
            timeoutSeconds: 30
            initialDelaySeconds: 15
          readinessProbe:
            exec:
              command: ["rabbitmqctl", "status"]
            initialDelaySeconds: 5
            timeoutSeconds: 10
          env:
            - name: RABBITMQ_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: RABBIT_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP