apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation
spec:
  selector:
    matchLabels:
      app: translation
  replicas: 2
  template:
    metadata:
      labels:
        app: translation
    spec:
      containers:
        - name: dev-translation
          image: petrovtoncho/translation
          ports:
            - name: t-port
              containerPort: 8082
          readinessProbe:
            httpGet:
              port: t-port
              path: /api/marvel/translation/isAlive
            initialDelaySeconds: 15
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              port: t-port
              path: /api/marvel/translation/isAlive
            initialDelaySeconds: 15
            timeoutSeconds: 30
          env:
            - name: RABBITMQ_HOSTNAME
              value: rabbit-service