apiVersion: v1
kind: Service
metadata:
  name: cdc-service
  labels:
    app: cdc-service
spec:
  type: NodePort
  externalIPs:
    - 192.168.0.204
  ports:
    - port: 8099
      name: cdc-service
      targetPort: 8099
      nodePort: 8099
    - port: 8080
      name: cdc-service1
      targetPort: 8080
      nodePort: 8080
  selector:
    app: cdc-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc-service
  labels:
    app: cdc-service
spec:
  selector:
    matchLabels:
      app: cdc-service
  template:
    metadata:
      name: cdc-service
      labels:
        app: cdc-service
    spec:
      containers:
        - name: cdc-service
          image: eventuateio/eventuateio-local-cdc-service
          ports:
            - containerPort: 8099
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/eventuate"
            - name: SPRING_DATASOURCE_USERNAME
              value: "eventuate"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "eventuate"
            - name: SPRING_DATASOURCE_TEST_ON_BORROW
              value: "true"
            - name: SPRING_DATASOURCE_VALIDATION_QUERY
              value: "SELECT 1"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"
            - name: EVENTUATELOCAL_CDC_DB_USER_NAME
              value: root
            - name: EVENTUATELOCAL_CDC_DB_PASSWORD
              value: rootp
            - name: EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID
              value: "111"
            - name: EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC
              value: "false"
            - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
              value: 10.1.61.103:2181
            - name: EVENTUATELOCAL_CDC_POLLING_INTERVAL_IN_MILLISECONDS
              value: "500"
            - name: EVENTUATELOCAL_CDC_MAX_EVENTS_PER_POLLING
              value: "100"
            - name: EVENTUATELOCAL_CDC_POLLING_RETRY_INTERVAL_IN_MILLISECONDS
              value: "500"
            - name: SPRING_PROFILE_ACTIVE
              value: "EventuatePolling"
            - name: EVENTUATELOCAL_CDC_READER_NAME
              value: "PostgresPollingReader"
            - name: EVENTUATE_CDC_TYPE
              value: "EventuateLocal"
