apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-service
spec:
  type: NodePort
  externalIPs:
    - 192.168.0.202
  ports:
    - port: 5432
      name: postgres
      targetPort: 5432
      nodePort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: eventuateio/eventuateio-local-postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "eventuate"
            - name: POSTGRES_PASSWORD
              value: "eventuate"
---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  externalIPs:
    - 192.168.0.203
  ports:
    - name: mongo-port
      port: 27017
      protocol: TCP
      nodePort: 27017
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
              name: mongo-port
          env:
            - name: MONGO_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: MONGO_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP