apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: NodePort
  externalIPs:
    - 192.168.0.201
  selector:
    app: kafka
  ports:
    - name: kafka-port
      port: 9092
      nodePort: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: eventuateio/eventuateio-local-kafka
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
#            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
#              value: zookeeper-service:2181
#            - name: KAFKA_ZOOKEEPER_CONNECT
#              value: zookeeper-service:2181
            - name: ZOOKEEPER_SERVERS
              value: "zookeeper-service:2181"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka
            - name: KAFKA_ADVERTISED_PORT
              value: '9092'
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
#            - name: KAFKA_INTER_BROKER_LISTENER_NAME
#              value: INSIDE
#            - name: KAFKA_LISTENERS
#              value: 'INSIDE://:9092'
#            - name: ADVERTISED_LISTENERS
#              value: "INSIDE://:9092"
#            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
#              value: "INSIDE:PLAINTEXT"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"