#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: zookeeper
#  labels:
#    app: zookeeper
#spec:
#  selector:
#    matchLabels:
#      app: zookeeper
#  template:
#    metadata:
#      name: zookeeper
#      labels:
#        app: zookeeper
#    spec:
#      containers:
#        - name: zookeeper
#          image: eventuateio/eventuateio-local-zookeeper
#          ports:
#            - containerPort: 2181
#          env:
#            - name: ZOOKEEPER_ID
#              value: "1"
#            - name: ZOOKEEPER_SERVER_1
#              value: zoo1
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: zookeeper-service
#spec:
#  type: NodePort
#  ports:
#    - name: client
#      port: 2181
#      nodePort: 2181
#      targetPort: 2181
#      protocol: TCP
#    - name: follower
#      port: 2888
#      protocol: TCP
#    - name: leader
#      port: 3888
#      protocol: TCP
#  selector:
#    app: zookeeper

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: NodePort
  selector:
    app: zookeeper
  externalIPs:
    - 192.168.0.200
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
      nodePort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: eventuateio/eventuateio-local-zookeeper
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 2181
#          tty: true
#          livenessProbe:
#            exec:
#              command:
#                - /opt/check.sh
#            initialDelaySeconds: 30
#            periodSeconds: 30
#          readinessProbe:
#            exec:
#              command:
#                - /opt/check.sh
#            initialDelaySeconds: 30
#            periodSeconds: 5
#      imagePullSecrets:
#        - name: regcred
